#!/usr/bin/env python3
"""Validate the K562/HepG2/GM12878 proof-of-concept outputs.

The script compares three groups when available:
  1. fine_tuned: sequences generated by the current trained checkpoint
  2. pretrained: reference sequences generated by the published checkpoint
  3. endogenous: real ENCODE-derived sequences from the original dataset

It intentionally does not run Enformer by default because that requires GPU
time. It writes sequence-level QC now and leaves an explicit Enformer status in
the report.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
from collections import defaultdict
from pathlib import Path

import pandas as pd

from project_utils import (
    cpg_count,
    ensure_dir,
    gc_content,
    infer_cell_type,
    jensen_shannon_distance,
    kmer_counts,
    normalize_seq,
    read_sequence_file,
    sequence_summary,
    validate_seq,
    write_json,
)

CELL_TYPES = ["K562", "HepG2", "GM12878"]
PRETRAINED_FILES = {
    "K562": "K562_ENCLB843GMH.txt",
    "HepG2": "HepG2_ENCLB029COU.txt",
    "GM12878": "GM12878_ENCLB441ZZZ.txt",
}
ENDO_FILE = "K562_hESCT0_HepG2_GM12878_12k_sequences_per_group.txt"
ENDO_TAG_MAP = {
    "K562_ENCLB843GMH": "K562",
    "HepG2_ENCLB029COU": "HepG2",
    "GM12878_ENCLB441ZZZ": "GM12878",
}
MOTIF_SEEDS = {
    "K562": ["GATA", "CACCTG", "CAGCTG", "GGAA"],
    "HepG2": ["TGTTT", "GTTTG", "AGGTCA", "TGACCT"],
    "GM12878": ["TTTGCAT", "GAAA", "GGAA", "ATGCAA"],
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--project-root", default=Path(__file__).resolve().parents[1])
    p.add_argument("--generated-dir", default=None, help="Fine-tuned generated sequence directory.")
    p.add_argument("--reference-dir", default=None)
    p.add_argument("--reports-dir", default=None)
    p.add_argument("--kmer", type=int, default=3)
    p.add_argument("--make-plots", action="store_true")
    return p.parse_args()


def default_generated_dirs(project_root: Path) -> list[Path]:
    dirs: list[Path] = []
    cache = os.environ.get("DNA_DIFFUSION_CACHE")
    if cache:
        dirs.append(Path(cache) / "training_final" / "generated")
    dirs.extend(
        [
            project_root / "generated",
            project_root / "outputs" / "generated",
            Path.home() / "dna_diffusion_cache" / "training_final" / "generated",
        ]
    )
    return dirs


def load_pretrained(reference_dir: Path) -> dict[str, list[str]]:
    data = {}
    for ct, fname in PRETRAINED_FILES.items():
        f = reference_dir / fname
        data[ct] = read_sequence_file(f) if f.exists() else []
    return data


def load_endogenous(reference_dir: Path) -> dict[str, list[str]]:
    f = reference_dir / ENDO_FILE
    out = {ct: [] for ct in CELL_TYPES}
    if not f.exists():
        return out
    df = pd.read_csv(f, sep="\t", usecols=["sequence", "TAG"])
    df["cell_type"] = df["TAG"].map(ENDO_TAG_MAP)
    df = df.dropna(subset=["cell_type"])
    df["sequence"] = df["sequence"].map(normalize_seq)
    df = df[df["sequence"].map(validate_seq)]
    for ct in CELL_TYPES:
        out[ct] = df.loc[df["cell_type"] == ct, "sequence"].drop_duplicates().tolist()
    return out


def load_generated(generated_dir: Path | None, project_root: Path) -> tuple[dict[str, list[str]], Path | None]:
    candidates = [generated_dir] if generated_dir else default_generated_dirs(project_root)
    for d in candidates:
        if d and Path(d).exists():
            out = {ct: [] for ct in CELL_TYPES}
            for f in Path(d).glob("*"):
                if not f.is_file():
                    continue
                ct = infer_cell_type(f.name)
                if ct in out:
                    out[ct].extend(read_sequence_file(f))
            if any(out.values()):
                return out, Path(d)
    return {ct: [] for ct in CELL_TYPES}, None


def motif_hits(seqs: list[str], cell_type: str) -> dict[str, float]:
    motifs = MOTIF_SEEDS[cell_type]
    denom = max(1, len(seqs))
    return {f"motif_{m}": sum(1 for s in seqs if m in s) / denom for m in motifs}


def build_metrics(groups: dict[str, dict[str, list[str]]], k: int) -> tuple[list[dict], dict]:
    rows = []
    detail = {}
    endogenous_sets = {ct: set(groups["endogenous"].get(ct, [])) for ct in CELL_TYPES}
    pretrained_sets = {ct: set(groups["pretrained"].get(ct, [])) for ct in CELL_TYPES}
    endogenous_kmers = {ct: kmer_counts(groups["endogenous"].get(ct, []), k) for ct in CELL_TYPES}

    for group_name, by_cell in groups.items():
        detail[group_name] = {}
        for ct in CELL_TYPES:
            seqs = by_cell.get(ct, [])
            summary = sequence_summary(seqs)
            seq_set = set(seqs)
            novelty_vs_endogenous = (
                len(seq_set - endogenous_sets[ct]) / len(seq_set) if seq_set else math.nan
            )
            novelty_vs_pretrained = (
                len(seq_set - pretrained_sets[ct]) / len(seq_set) if seq_set else math.nan
            )
            jsd = jensen_shannon_distance(kmer_counts(seqs, k), endogenous_kmers[ct])
            row = {
                "group": group_name,
                "cell_type": ct,
                **summary,
                "novelty_vs_endogenous": novelty_vs_endogenous,
                "novelty_vs_pretrained": novelty_vs_pretrained,
                f"{k}mer_jsd_vs_endogenous": jsd,
                **motif_hits(seqs, ct),
            }
            rows.append(row)
            detail[group_name][ct] = row
    return rows, detail


def write_report(path: Path, metrics: list[dict], generated_path: Path | None) -> None:
    fine_rows = [r for r in metrics if r["group"] == "fine_tuned"]
    fine_complete = generated_path is not None and all(r["n"] > 0 for r in fine_rows)
    lines = [
        "# Cell-Line Proof-of-Concept Report",
        "",
        "## Completion State",
        "",
        f"- Fine-tuned generated directory: `{generated_path}`" if generated_path else "- Fine-tuned generated directory: not found",
        f"- POC generation complete: {'yes' if fine_complete else 'no'}",
        "- Enformer validation: not run by this script; run the GPU Enformer pipeline after generation.",
        "",
        "## Sequence QC Summary",
        "",
    ]
    header = [
        "group",
        "cell_type",
        "n",
        "unique",
        "duplicate_rate",
        "gc_mean",
        "cpg_mean",
        "novelty_vs_endogenous",
        "novelty_vs_pretrained",
    ]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("| " + " | ".join(["---"] * len(header)) + " |")
    for r in metrics:
        vals = []
        for h in header:
            v = r[h]
            vals.append(f"{v:.3f}" if isinstance(v, float) and not math.isnan(v) else str(v))
        lines.append("| " + " | ".join(vals) + " |")
    lines.extend(
        [
            "",
            "## Go/No-Go Notes",
            "",
            "- Go to hematopoietic implementation only after fine-tuned sequences exist for all three cell types.",
            "- Keep pretrained and endogenous references as controls for all downstream comparisons.",
            "- If fine-tuned sequences are not novel or drift strongly from endogenous GC/k-mer distributions, revisit training length and pretrained initialization.",
            "",
        ]
    )
    path.write_text("\n".join(lines))


def make_plots(metrics: list[dict], out_dir: Path) -> None:
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        return
    df = pd.DataFrame(metrics)
    for value in ["gc_mean", "cpg_mean", "duplicate_rate"]:
        ax = df.pivot(index="cell_type", columns="group", values=value).plot(kind="bar")
        ax.set_title(value)
        ax.figure.tight_layout()
        ax.figure.savefig(out_dir / f"{value}.png", dpi=160)
        plt.close(ax.figure)


def main() -> None:
    args = parse_args()
    project_root = Path(args.project_root)
    reference_dir = Path(args.reference_dir) if args.reference_dir else project_root / "reference_data"
    reports_dir = ensure_dir(args.reports_dir or project_root / "reports")

    generated, generated_path = load_generated(Path(args.generated_dir) if args.generated_dir else None, project_root)
    groups = {
        "fine_tuned": generated,
        "pretrained": load_pretrained(reference_dir),
        "endogenous": load_endogenous(reference_dir),
    }
    metrics, detail = build_metrics(groups, args.kmer)

    pd.DataFrame(metrics).to_csv(reports_dir / "cellline_poc_metrics.csv", index=False)
    write_json(reports_dir / "cellline_poc_metrics.json", detail)
    write_report(reports_dir / "cellline_poc_report.md", metrics, generated_path)
    if args.make_plots:
        make_plots(metrics, ensure_dir(reports_dir / "figures"))

    print(f"Wrote {reports_dir / 'cellline_poc_report.md'}")


if __name__ == "__main__":
    main()
